OHS_BASE_URL = "https://www.oregonhumane.org/"
ADOPT_ENDPOINT = OHS_BASE_URL + "/adopt/"

RESULT_ITEM_CLASS = "result-item"

TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN"
TWILIO_PHONE_NUMBER = "TWILIO_PHONE_NUMBER"

SEND_TO_PHONE_NUMBERS = "SEND_TO_PHONE_NUMBERS"
